output_folder:              analysis_output
coverage_filters:           [0, 10]
strand_bias_filters:        [0.0, 0.2]
gaps_filters:               [1.0, 0.8]

samples:                    metadata/samples.csv
variant_calls:              metadata/variant_calls.csv
variant_calls_probe_length: 25
truth_probes_flank_length:  21

number_of_points_in_ROC_curve: 100