# installation configs
singularity_image: rmcolq-pandora-dev-pandora.simg
git_commit: ed953d1
mem_mb: 2000

# fixed configs
window_size: 19
kmer_size: 31

# benchmarking configs
#threads: [1, 2, 4, 8, 16]
threads: [1, 2]

# data configs
# TODO: improve this with csv files
data_folder: sample_data/
PRGs: [prg1.fa, prg2.fa]
reads_to_map: [reads1.fq, reads2.fq]
samples_to_map: [samples1.tsv, samples2.tsv]