output_folder: samtools_calls

sample_data_dir: /hps/nobackup/iqbal/leandro/pandora_analysis_pipeline/data_20_way/data_for_pipeline/samples
samples: [  063_STEC,
            CFT073,
            Escherichia_coli_MINF_1A,
            Escherichia_coli_MINF_1D,
            Escherichia_coli_MINF_2E,
            Escherichia_coli_MINF_7C,
            Escherichia_coli_MINF_8D,
            Escherichia_coli_MINF_9A,
            Escherichia_coli_MSB1_1A,
            Escherichia_coli_MSB1_3B,
            Escherichia_coli_MSB1_3I,
            Escherichia_coli_MSB1_4E,
            Escherichia_coli_MSB1_4I,
            Escherichia_coli_MSB1_6C,
            Escherichia_coli_MSB1_6J,
            Escherichia_coli_MSB1_7A,
            Escherichia_coli_MSB1_7C,
            Escherichia_coli_MSB1_8B,
            Escherichia_coli_MSB1_8G,
            Escherichia_coli_MSB1_9D,
            Escherichia_coli_MSB1_9I,
            Escherichia_coli_MSB2_1A,
            H131800734
]

references_csv: /hps/nobackup/iqbal/leandro/pandora_analysis_pipeline/references/references.csv

coverages: [100x]
subsamplings: [random]
technologies: [illumina]